const trans = `BalconyGazebo.jpg  bbq25.jpg            downstairsgarden.jpg  living7.jpg           outdoor9.jpg             room17.jpg             room32.jpg         room53.jpg           room68.jpg
bbq10.jpg          bbq26.jpg            downstairspool.jpg    living8.jpg           outdoorcouchandpool.jpg  room18.jpg             room34.jpg         room54.jpg           room69.jpg
bbq11.jpg          bbq27.jpg            footer.jpg            living9.jpg           poolandcouch.jpg         room19.jpg             room35.jpg         room55.jpg           room6bed.jpg
bbq12.jpg          bbq28.jpg            GazeboStairs.jpg      logo-large-dark.png   pool.jpg                 room1bathroomdoor.jpg  room36.jpg         room56.jpg           room6couchandbed.jpg
bbq13.jpg          bbq29.jpg            kara1.jpg             logo-large-light.png  PoolLounger.jpg          Room1BedPool.jpg       room37.jpg         room57.jpg           room6couch.jpg
bbq14.jpg          bbq2.jpg             kara2.jpg             logo-small-dark.png   PoolParkinglot.jpg       room22.jpg             room38.jpg         room58.jpg           roomk21.jpg
bbq15.jpg          bbq30.jpg            kara3.jpg             lounge.jpg            room110.jpg              room23.jpg             room39.jpg         room59.jpg           social1.jpg
bbq16.jpg          bbq3.jpg             living10.jpg          outdoor10.jpg         room111.jpg              room24.jpg             room3bathroom.jpg  room5bedanddoor.jpg  social3.jpg
bbq17.jpg          bbq4.jpg             living11.jpg          outdoor11.jpg         room112.jpg              room25.jpg             room4backwall.jpg  room5bed.jpg         social4.jpg
bbq18.jpg          bbq5.jpg             living12.jpg          outdoor12.jpg         room113.jpg              room26.jpg             room4bed1.jpg      room610.jpg          social6.jpg
bbq19.jpg          bbq6.jpg             living13.jpg          outdoor1.jpg          room114.jpg              room27.jpg             room4bedend.jpg    room61.jpg           social.jpg
bbq1.jpg           bbq7.jpg             living1.jpg           outdoor2.jpg          room1-1.jpg              room2bathroom.jpg      room4bed.jpg       room62.jpg           upstairsgazebo.jpg
bbq20.jpg          bbq8.jpg             living2.jpg           outdoor3.jpg          room-1-2.jpg             room2bed.jpg           room4desk.jpg      room63.jpg           work1.jpg
bbq21.jpg          bbq9.jpg             living3.jpg           outdoor4.jpg          room-1-3.jpg             Room2BedWardrobe.jpg   room4full.jpg      room64.jpg           work2.jpg
bbq22.jpg          coworking1.jpg       living4.jpg           outdoor6.jpg          room-1-4.jpg             room310.jpg            room4wardrobe.jpg  room65.jpg           work.jpg
bbq23.jpg          coworking.jpg        living5.jpg           outdoor7.jpg          room15.jpg               room311.jpg            room51.jpg         room66.jpg
bbq24.jpg          downstairscouch.jpg  living6.jpg           outdoor8.jpg          room16.jpg               room31.jpg             room52.jpg         room67.jpg`

const transed = [
    "BalconyGazebo.jpg",
    "bbq25.jpg",
    "downstairsgarden.jpg",
    "living7.jpg",
    "outdoor9.jpg",
    "room17.jpg",
    "room32.jpg",
    "room53.jpg",
    "room68.jpg",
    "bbq10.jpg",
    "bbq26.jpg",
    "downstairspool.jpg",
    "living8.jpg",
    "outdoorcouchandpool.jpg",
    "room18.jpg",
    "room34.jpg",
    "room54.jpg",
    "room69.jpg",
    "bbq11.jpg",
    "bbq27.jpg",
    "footer.jpg",
    "living9.jpg",
    "poolandcouch.jpg",
    "room19.jpg",
    "room35.jpg",
    "room55.jpg",
    "room6bed.jpg",
    "bbq12.jpg",
    "bbq28.jpg",
    "GazeboStairs.jpg",
    "logo-large-dark.png",
    "pool.jpg",
    "room1bathroomdoor.jpg",
    "room36.jpg",
    "room56.jpg",
    "room6couchandbed.jpg",
    "bbq13.jpg",
    "bbq29.jpg",
    "kara1.jpg",
    "logo-large-light.png",
    "PoolLounger.jpg",
    "Room1BedPool.jpg",
    "room37.jpg",
    "room57.jpg",
    "room6couch.jpg",
    "bbq14.jpg",
    "bbq2.jpg",
    "kara2.jpg",
    "logo-small-dark.png",
    "PoolParkinglot.jpg",
    "room22.jpg",
    "room38.jpg",
    "room58.jpg",
    "roomk21.jpg",
    "bbq15.jpg",
    "bbq30.jpg",
    "kara3.jpg",
    "lounge.jpg",
    "room110.jpg",
    "room23.jpg",
    "room39.jpg",
    "room59.jpg",
    "social1.jpg",
    "bbq16.jpg",
    "bbq3.jpg",
    "living10.jpg",
    "outdoor10.jpg",
    "room111.jpg",
    "room24.jpg",
    "room3bathroom.jpg",
    "room5bedanddoor.jpg",
    "social3.jpg",
    "bbq17.jpg",
    "bbq4.jpg",
    "living11.jpg",
    "outdoor11.jpg",
    "room112.jpg",
    "room25.jpg",
    "room4backwall.jpg",
    "room5bed.jpg",
    "social4.jpg",
    "bbq18.jpg",
    "bbq5.jpg",
    "living12.jpg",
    "outdoor12.jpg",
    "room113.jpg",
    "room26.jpg",
    "room4bed1.jpg",
    "room610.jpg",
    "social6.jpg",
    "bbq19.jpg",
    "bbq6.jpg",
    "living13.jpg",
    "outdoor1.jpg",
    "room114.jpg",
    "room27.jpg",
    "room4bedend.jpg",
    "room61.jpg",
    "social.jpg",
    "bbq1.jpg",
    "bbq7.jpg",
    "living1.jpg",
    "outdoor2.jpg",
    "room1-1.jpg",
    "room2bathroom.jpg",
    "room4bed.jpg",
    "room62.jpg",
    "upstairsgazebo.jpg",
    "bbq20.jpg",
    "bbq8.jpg",
    "living2.jpg",
    "outdoor3.jpg",
    "room-1-2.jpg",
    "room2bed.jpg",
    "room4desk.jpg",
    "room63.jpg",
    "work1.jpg",
    "bbq21.jpg",
    "bbq9.jpg",
    "living3.jpg",
    "outdoor4.jpg",
    "room-1-3.jpg",
    "Room2BedWardrobe.jpg",
    "room4full.jpg",
    "room64.jpg",
    "work2.jpg",
    "bbq22.jpg",
    "coworking1.jpg",
    "living4.jpg",
    "outdoor6.jpg",
    "room-1-4.jpg",
    "room310.jpg",
    "room4wardrobe.jpg",
    "room65.jpg",
    "work.jpg",
    "bbq23.jpg",
    "coworking.jpg",
    "living5.jpg",
    "outdoor7.jpg",
    "room15.jpg",
    "room311.jpg",
    "room51.jpg",
    "room66.jpg",
    "bbq24.jpg",
    "downstairscouch.jpg",
    "living6.jpg",
    "outdoor8.jpg",
    "room16.jpg",
    "room31.jpg",
    "room52.jpg",
    "room67.jpg"
  ]

export default { trans, transed }